### PR TITLE
Chapter 5

### PR DESCRIPTION
**Pull request by gpoirier**

### CODE REVIEW

**Comment by MasseGuillaume** [comment]
@masseguillaume

**Comment by gpoirier** [comment]
@MasseGuillaume, if you want to take a look.

**Comment by MasseGuillaume** [comment]
@gpoirier suggesting specs2 + scalcheck
http://stackoverflow.com/questions/6263108/how-to-use-specs2-with-scalacheck-to-automate-testing-of-string-arguments

note that utest is really lightweight
https://github.com/lihaoyi/utest/issues/2

**Comment by gpoirier** [comment]
@MasseGuillaume I added tests.

**Pull request merged**
